### ISSUE TITLE
Please create a secret to push p2 repo to gh-pages

### ISSUE THREAD

**Issue by mickaelistria** [rgrunber/eclipse.jdt.ls.client#3]
Please create a secret to push to gh-pages from the CI build (using https://github.com/marketplace/actions/publish-to-github-pages ).

**Comment by rgrunber** [comment]
Can you use https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret ? I have used it to publish to the Github Releases page.

**Comment by mickaelistria** [comment]
Thanks, looks like a custom token is not needed.
